[tool.poetry]
name = "sqlalchemy-crud"
version = "0.1.0"
description = "Basic C.R.U.D for SQLAlchemy models"
authors = ["Clayton Black"]

[tool.poetry.dependencies]
python = "^3.8"
SQLAlchemy = "^1.3.19"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
